version: '3.8'

services:
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    ports:
      - "4080:4080"
    volumes:
      - zinc_data:/data
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=atd5NF35mX£k

volumes:
  zinc_data: