version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8004:81"
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile

  web:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    depends_on:
      - api